### ISSUE TITLE
Feature-Request: Automatically set stories for mocha describe

### ISSUE THREAD

**Issue by weblogixx** [webdriverio-boneyard/wdio-allure-reporter#11]
Hi,

first of all, let me thank you for this great software. Makes reporting of tests much easier to work with.
I have a feature request for the reporter, but do not know if this is the right place.

When you use tests via wdio testrunner with Mocha as a framework, you will have tests that roughly look like this:

``` javascript

describe('my page', () => {

  describe('when I visit it the first time', () => {

    it('should do something', () => {
      expect(true).to.be.true; // whatever
    });
  });

  describe('when I visit it the second time', () => {

    it('should do something else', () => {
      expect(true).to.be.true; // whatever
    });

    it('and this here, too', () => {
      expect(true).to.be.true; // whatever
    });
  });
});
```

Currently, the allure report packs every describe block as a suite, meaning you got 3 of those:
1. The empty "my page" one
2. The "when I visit first time" one, including its subs
3. The "second time..." one, including its subs

In the allure dashboard, you are able to find them in xunit reports, but not as behaviours because they are not structured correctly and also lack the feature/story stuff.

My suggestions would be:
1. Make the first describe block the feature
2. Make each of the inner describe blocks a story
3. Leave each of the it blocks as tests in the way they are currently.

This would make it an even more useable reporting tool. Maybe this is even possible out of the box and I was not able to find it?

**Comment by just-boris** [comment]
Hello. This is a reasonable feature request. But I think it cannot be implemented in that way because not everybody has that structure for tests.

Also, Mocha has a [tagging feature](https://github.com/mochajs/mocha/wiki/Tagging), and I consider using this thing for create user stories structure.

**Comment by weblogixx** [comment]
Seems like a nice addition! It would be much easier if wdio-mocha-framework would expose the current allure instance. However I was not able get it to work correctly. In standalone examples it works like a charm, but when running via wdio, everything is different.

**Comment by gronke** [comment]
Allure displays the results in two dimensions. The first is the suite, the second is a case within that suite.

Without usage of feature/story labels in my use-cases it made the most sense to use first level describe blocks as Allure suite and all nested suites and tests within that as Allure cases. @weblogixx in [your example](https://github.com/webdriverio/wdio-allure-reporter/issues/11#issue-148329284) this would result in the following structure

1. My Page
  1. when I visit it the first time >> should do something
  2. when I visit it the second time >> should do something else
  3. when I visit it the second time >> and this here, too

In a (now closed) Pull-Request #9 we had a discussion around passing the Allure adapter instance to the test framework instance (in this case Mocha), but @christian-bromann mentioned it is more elegant to [trigger a custom `allure:addLabel` event](https://github.com/webdriverio/wdio-allure-reporter/pull/9#issuecomment-212168901) that could be picked up by this reporter.

Usually the test framework does not care about the origin of a test case, but sometimes it's neat to give developers that extra information. That means the story/feature labels can be invoked manually from within a test runner.

For that to work the Allure adapter must be continuously keep track of running tests to be able to relate the manually triggered event to the case that should be labeled. We're working on this feature in #8.

**Comment by weblogixx** [comment]
Hi @gronke,

I think I will leave it the way I currently use it until the new features arrive in a new version of the reporter.
Thank you for the constant work (and giving feedback!).

**Comment by nzhenry** [comment]
> ...I think it cannot be implemented in that way because not everybody has that structure for tests.

The fact that not everybody has that structure does not necessarily mean it cannot be implemented that way.

**Comment by nzhenry** [comment]
I am using webdriver.io and jasmine to run my end-to-end tests and it would be nice if the "Behaviours" section of the allure report reflected the hierarchical nature of my tests. Is this possible?

Currently the "Behaviours" section has all my tests in a group named "Without story" inside a group named "Without feature". How can I get this to work properly?

**Comment by gronke** [comment]
We need to map between the actual test structure and the Allure reporter output anyway. I doubt we find the solution that works for everybody, so what about making the mapper function an optional, configurable option? For me [the mapping mentioned above](https://github.com/webdriverio/wdio-allure-reporter/issues/11#issuecomment-219276625) works pretty well, but I can imagine other cases where it would not be the best fit.

**Comment by just-boris** [comment]
Hello! Now the thing is Allure by design has Suite->Case and Feature->Story structure because we didn't have other kinds of tests. 

We understand that it does not work well with some test frameworks, especially with JavaScript tools, which usually supports deeply nested `describe` blocks. I think the best solution will be support tree structure of tests in Allure-core. I asked core team about that, and will copy their response here.

Once it will be provided, this issue can be easily solved.

**Comment by gronke** [comment]
@just-boris support for nested describe blocks in Allure would be really awesome. Even if I'm using nested describe blocks, I like the flat structure of the test results. Having Allure keep track of nested suites and concatenating their titles is very welcome.

**Comment by BorisOsipov** [comment]
Close due inactive.
