### ISSUE TITLE
All skipped steps in run displayed even when suites are collapsed when using with wdio-cucumber-framework 

### ISSUE THREAD

**Issue by osmolyar** [webdriverio-boneyard/wdio-allure-reporter#115]
All skipped steps in a run are displayed under the suites on the Behaviors view even when suites are collapsed.  They are also displayed when navigating to one suite from the Overview pane even if they are not part of that suite.

For example, in the below image, with all suites collapsed, all the Skipped steps (from 'Access Control' suite) are displayed:

![image](https://user-images.githubusercontent.com/15637471/40239726-de7cde98-5a84-11e8-9eb7-9fccea1d72c6.png)

They are also displayed if one of the 'other' suites is open or navigated to from 'Overview', e.g. in the below image all the skipped steps from 'Access Control' suite are still displayed when another suite is open:

![image](https://user-images.githubusercontent.com/15637471/40239837-31937ba0-5a85-11e8-9495-1286bb1fc327.png)

It's more confusing when the last suite is open because then the unrelated Skipped steps are displayed directly under the tests for the other open suite:

![image](https://user-images.githubusercontent.com/15637471/40239942-6b98b82e-5a85-11e8-8e68-98e3b332486f.png)

**Comment by BorisOsipov** [comment]
@osmolyar can you share *.xml file with such skipped tests?

**Comment by osmolyar** [comment]
Here is a zipped file of two of the *testsuite.xml files with steps reported as 'Skipped' (status =undefined):.

[Skipped_undefined.zip](https://github.com/webdriverio/wdio-allure-reporter/files/2017444/Skipped_undefined.zip)

Another thing is that the skipped tests *don't* appear with the other steps inside the test cases they belong to, for example the steps pictured above belong with test cases like:

![image](https://user-images.githubusercontent.com/15637471/40241676-97dd4432-5a89-11e8-847e-20f28123c6a0.png)

**Comment by BorisOsipov** [comment]
another group of questions:

1) which wdio-cucumber\allure versions do you use?
2) add allure reporterOptions and cucumber configuration.
3) how do you skip such test in cucumber?

**Comment by osmolyar** [comment]
Actually it is working correctly in another installation, using your latest 0.6.0 version, so this item can be closed.

To answer the questions:
1. "wdio-cucumber-framework": "^1.1.0",
  "wdio-allure-reporter": "^0.3.2",

2.    reporters: `   reporters: ['spec','junit','dot','allure'],
    reporterOptions: {
        json: {
            outputDir: 'testResults'
        },
        junit: {
            outputDir: 'testResults',
        },
        allure: {
            outputDir: 'allure-results',
            useCucumberStepReporter: true
        },
    },`

Cucumber config:
`   cucumberOpts: {
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> filetype:compiler used for processing required features
        compiler: [
            'js:babel-register',
        ],
        // <boolean< Treat ambiguous definitions as errors
        failAmbiguousDefinitions: true,
        // <boolean> invoke formatters without executing steps
        // dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> Enable this config to treat undefined definitions as
        // warnings
        ignoreUndefinedDefinitions: false,
        // <string[]> ("extension:module") require files with the given
        // EXTENSION after requiring MODULE (repeatable)
        name: [],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <string[]> (file/dir) require files before executing features
        require: [
            './features/step_definitions/*',
        ],
        // <string> specify a custom snippet syntax
        snippetSyntax: undefined,
        // <boolean> fail if there are any undefined or pending steps
        strict: true,
        // <string> (expression) only execute the features or scenarios with
        // tags matching the expression, see
        // https://docs.cucumber.io/tag-expressions/
        tagExpression: 'not @Pending',
        // <boolean> add cucumber tags to feature or scenario name
        tagsInTitle: false,
        // <number> timeout for step definitions
        timeout: 2000000,
    },
`

3.  The steps (these are steps, not tests; it's because version < 0.6.0 that they look like tests) are skipped automatically because prior steps in the same TC failed.

Thanks

**Comment by christian-bromann** [comment]
@BorisOsipov why just closing the issue?

**Comment by BorisOsipov** [comment]
@christian-bromann I guess misclick. thank you for pointing that out

**Comment by BorisOsipov** [comment]
@osmolyar
1) as I see your xml files are not generated with `useCucumberStepReporter` option.
2) > Skipped steps are displayed directly under the tests for the other open suite:
It looks like bug. I will see.

**Comment by BorisOsipov** [comment]
@osmolyar does it still reproduces?

For me it is ok
![2018-08-31_1149](https://user-images.githubusercontent.com/6514276/44903134-69284c80-ad14-11e8-8913-6d574a221d8c.png)

**Comment by osmolyar** [comment]
It is working fine - from May 18 comment "Actually it is working correctly in another installation, using your latest 0.6.0 version, so this item can be closed."
