### ISSUE TITLE
Report Broken when using "useCucumberStepReporter":"true"

### ISSUE THREAD

**Issue by miguelsantos500** [webdriverio-boneyard/wdio-allure-reporter#130]
When I use allure-reporter to generate a Cucumber Report, using "useCucumberStepReporter":"true" **and** have more than one Scenario in one Feature, the generated report is the following:

Features:
```
Feature: Frontend Sanity


  Scenario: Login
    Given I login to Selfcare
      | user                  |
      | portalr27@outlook.com |

    Then I navigate to "Orders" Page

    Then I check that we are in "Orders" Page
  Scenario: Login

    Then I navigate to "Orders" Page

    Then I check that we are in "Orders" Page
  Scenario: Login

    Then I navigate to "Orders" Page

    Then I check that we are in "Orders" Page

```
```
Feature: Orders

  Scenario: Create Order
    Given I "Internal Delete" "Client" "orders_customer_01"
      | fromDB |
      | true   |

    When Via "Internal_SDP" API, I "Create" "Subscription" "orders_subs_01"
      | customerId         | customerName       | operatorId   |
      | orders_customer_01 | orders_customer_01 | [operatorId] |
    Then API status code should be "201"

  #CREATE SERVICE
    When Via "Internal_SDP" API, I "Update" "Subscription" "orders_subs_01"
      | ixsId          | adminName         | adminEmail        | adminLogin        |
      | IXS.IOrders.01 | iorders1@mail.com | iorders1@mail.com | iorders1@mail.com |
    Then API status code should be "201"

    Then I set password for user
      | user              | realm               |
      | iorders1@mail.com | selfcare.[operator] |
#
    Given I login to Selfcare
      | user              | password  |
      | iorders1@mail.com | 123qwerty |

    When I navigate to "Orders" Page

    And I create Order with the following parameters
      | amount | format         | robustnessLevel | simType | name | contact   | address      |
      | 2      | FullSize (2FF) | Robust          | USIM    | name | 912345677 | Morada Teste |

    Then I check that the first order has the following info
      |Canal do pedido|Nome do utilizador   | Estado    |
      |Portal         |iorders1@mail.com    | Submetido | 
```

![image](https://user-images.githubusercontent.com/16048818/43962442-a1dede92-9caf-11e8-8291-dff309ce00fc.png)
![image](https://user-images.githubusercontent.com/16048818/43962517-c7487c88-9caf-11e8-920f-cd627a9656be.png)

If I unset  "useCucumberStepReporter", the report is correctly generated (with every step being treated as on test):
![image](https://user-images.githubusercontent.com/16048818/43963132-64d29bc2-9cb1-11e8-99e8-9f6f9b8b3eda.png)
![image](https://user-images.githubusercontent.com/16048818/43963148-71df98d8-9cb1-11e8-84d6-220ce4072653.png)

Versions: 

- wdio-cucumber-framework@2.0.1
- wdio-allure-reporter@0.6.0
- webdriverio@4.12.0

**Comment by BorisOsipov** [comment]
Hi @miguelsantos500 which wdio-cucumber-framework version did you use?

**Comment by miguelsantos500** [comment]
Sorry, updated above.

**Comment by BorisOsipov** [comment]
@miguelsantos500 try to update wdio-cucumber to the latest v2.2.2.
If it doesn't help you may go back to v1.1.1 for me it works.

**Comment by miguelsantos500** [comment]
Works with version 2.2.2, therefore I'm closing the issue.
However, is "useCucumberStepReporter" supposed to aggregate Cucumber tests by Feature?
Wouldn't it make more sense to aggregate by Scenario?


![image](https://user-images.githubusercontent.com/16048818/43964789-7fbf2212-9cb5-11e8-98d9-548f2ff630f5.png)

**Comment by BorisOsipov** [comment]
In your screen reporter works incorrect.
Steps from different scenarios should not join in one.

@miguelsantos500 make scenario name unique
instead of 
Scenario: Login
Scenario: Login
Scenario: Login

make

Scenario: Login smth1
Scenario: Login smth2
Scenario: Login smth3

maybe it help

BTW I didn't test it fully with wdio-cucumber v2+ and won't fix any bug cuz now v2 works incorrect for me and we port this to wdio v5
