### ISSUE TITLE
Allure report Jenkins plugin doesn't distinguish among versions of same browser

### ISSUE THREAD

**Issue by osmolyar** [webdriverio-boneyard/wdio-allure-reporter#131]
Ref. issue #102,  With wdio-allure-reporter version 0.7.0.

With a Jenkins run with tests recorded as being run on both IE10 and IE11 in the Jenkins report, the Allure plugin-generated report attached to the same Jenkins job only reports the tests as run once, on 'internet explorer'

**Comment by BorisOsipov** [comment]
yes, because we don't add browser version as test argument :(

**Comment by osmolyar** [comment]
Is it possible to consider doing so?  Also why is this in the boneyard?  Is wdio moving away from allure 1 support?

**Comment by christian-bromann** [comment]
> Also why is this in the boneyard? Is wdio moving away from allure 1 support?

This package has been moved to the new v5 repository

**Comment by BorisOsipov** [comment]
@osmolyar I will make hot fix for this and port it to v5 after

**Comment by osmolyar** [comment]
@BorisOsipov thank you so much!!

**Comment by christian-bromann** [comment]
Let's continue convo in #133
