### ISSUE TITLE
Scenarios are grouped in the Suite display and gets appeneded as well. 

### ISSUE THREAD

**Issue by id4automation** [webdriverio-boneyard/wdio-allure-reporter#132]
Hi , I am using the below versions

1) I am not seeing the right number of scenarios in my Allure report. Instead I see Number of test steps executed as Number of scenarios. I reckon this was fixed in wdio-allure-report. But it is still not working as expected.

2) The test suite is not displaying the scenario individually. Fo some reason it is combining multiple scenario and keeps appending with the previous data. Refer the attached snapshot. Landing is the feature file name and every new scenario starts with 01, 02 number as prefix. Kindly let me know how to fix that. 

I am using

> wdio-cucumber-framework@ 2.2.2.
> wdio-allure-reporter@ 0.7.0
> cucumber @4.2.1.

This is the wdio.conf.js settings
```
     reporters: ['dot','allure'],
     reporterOptions: {
        allure: {
            outputDir: 'allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
            useCucumberStepReporter: false
        }
    },
```

![image](https://user-images.githubusercontent.com/41796998/44085906-cba51ca4-9fb2-11e8-8e39-fe642ab4a859.png)

**Comment by id4automation** [comment]
Thanks. that did the magic.

**Comment by christian-bromann** [comment]
I guess we can close this then.
