### ISSUE TITLE
Cucumber: Common steps are merged into one in the allure reports.

### ISSUE THREAD

**Issue by NaveenThiyagarajan** [webdriverio-boneyard/wdio-allure-reporter#138]
If there are common steps in a scenario then the allure reports the result for only one(the latest/last step) and the old ones are added to the retry section of that step.

Based on my understanding this is fixed in "allure-ruby-commons" (https://github.com/allure-framework/allure-cucumber/pull/65). But i am really not sure about internal arch but i can see this "wdio-allure-reporter" uses `allure-js-commons`. So i guess we need the same fix in here as well.

Here is the orginal issue: https://github.com/allure-framework/allure-cucumber/issues/41

**Comment by BorisOsipov** [comment]
Setting `useCucumberStepReporter: true` in config should help. See [config description](useCucumberStepReporter: false)
