### ISSUE TITLE
Cucumber: Scenario marked passed but all the steps in there are pending.

### ISSUE THREAD

**Issue by NaveenThiyagarajan** [webdriverio-boneyard/wdio-allure-reporter#139]
Hi Team,

I have the below package versions:
"wdio-allure-reporter": "^0.7.0",
"wdio-cucumber-framework": "^2.2.3",
"webdriverio": "^4.13.2"

Running the test with `useCucumberStepReporter: true`.

After running the tests the allure report generated is marking the scenario(test case) passed even when all the steps in there are pending(aka: Not executed).

![scenariomarkedpassed](https://user-images.githubusercontent.com/26540915/46531222-0fd6ae80-c8ba-11e8-9717-02bfc6e4c61f.png)

**Comment by BorisOsipov** [comment]
@NaveenThiyagarajan yes it is. feel free to propose a PR.

**Comment by NaveenThiyagarajan** [comment]
@BorisOsipov . I take back my previous comment. I have pushed a PR. Please review. Thank you..

**Comment by NaveenThiyagarajan** [comment]
Issue fixed as part of `0.8.3`. Closing the ticket.
