### ISSUE TITLE
Add Issues / TMS links support

### ISSUE THREAD

**Issue by sskorol** [webdriverio-boneyard/wdio-allure-reporter#140]
Currently, it's not possible to add corresponding links to test results report.
Seems like it's not a huge deal according to https://github.com/allure-framework/allure-js-commons/issues/13#issuecomment-218682337
Will raise a PR for that.

**Comment by christian-bromann** [comment]
Let's make sure to port this to v5

**Comment by BorisOsipov** [comment]
@christian-bromann 	it was ported in https://github.com/webdriverio/webdriverio/pull/2989
