### ISSUE TITLE
Additional argument support

### ISSUE THREAD

**Issue by andrcuns** [webdriverio-boneyard/wdio-allure-reporter#142]
Hey guys,
Would You consider adding additional custom arguments, like the default browser name?
We have an issue that we run same scenario in multiple resolutions for example and it get's merged as single execution. Not 100% sure if it would help to distinguish them, but I think it should.

**Comment by BorisOsipov** [comment]
I am not sure about scenario resolution. Someone will come tomorrow and say "we run same scenario in multiple OS" :)
Need to add some generic logic how to add properties from capabilities as arguments. Or not only from capabilities.

**Comment by andrcuns** [comment]
It's the same as adding description, tms or issue, isn't it? Just need to expose the command that adds additional argument. At least in java all these manual manipulations were extremely easy.
Or I'm not understanding this correctly?
Capability is also fine, though I'm not sure if it wouldn't cause some problems in the future as I saw in v5 there is a proposal to validate capabilities against W3C standard.

**Comment by BorisOsipov** [comment]
>It's the same as adding description, tms or issue, isn't it?

It requires to add such args for each test manually(e.g. wrap mocha `it` function). does it suit you?

**Comment by BorisOsipov** [comment]
I mean you can't add description\issue\arg in before test hook because there is no test in reporter yet.

**Comment by andrcuns** [comment]
I can do it in after hook, at least I can add description that way for example. It's also how we attach browser logs to report etc. While I agree that generic way from capabilities would be better, I think it's problematic to find a generic way which would handle all the cases. So I think additional method in reporter like addArgument should be sufficient in all cases.

**Comment by BorisOsipov** [comment]
if it works in after hooks it's ok.

>So I think additional method in reporter like addArgument should be sufficient in all cases.

Agree. Thanks for clarifications.

**Comment by andrcuns** [comment]
I can try running it locally and test it out if it works like I imagine it should :) And submit a PR if it does here and I guess in v5. Shouldn't be more than few lines of code.

**Comment by christian-bromann** [comment]
Let's continue convo in #143
