### ISSUE TITLE
Allure-results folder is getting bigger and bigger

### ISSUE THREAD

**Issue by dalenguyen** [webdriverio-boneyard/wdio-allure-reporter#147]
Hi, I have a question about the results folder. What is the best practice to deal with it? Because it will generate a lot of files everytime I run the test. Are there any methods to clean it? Thanks,

**Comment by BorisOsipov** [comment]
It is up to you. This question is not related to reporter itself. Please, ask in official allure gitter chanel https://gitter.im/allure-framework/allure-core

**Comment by dalenguyen** [comment]
Thanks @BorisOsipov
