### ISSUE TITLE
How to show failed/broken tests in email notification?

### ISSUE THREAD

**Issue by sanyco92** [webdriverio-boneyard/wdio-allure-reporter#149]
Hello! Currently, I'm using allure reporter with webdriver.io. Tests run on Jenkins environment and every night I'm getting email notifications from Jenkins. For this, I'm using the groovy script (https://gist.github.com/letsrokk/50a3ffc8ad5af8896ce78e62fe1e8cb5) and it looks good. But I need to see which test cases are failed and broken in the email notification. Is there a way to show in email report names of failed test cases and the reason why they're failed?

**Comment by christian-bromann** [comment]
How is this related to wdio-allure-reporter?

**Comment by BorisOsipov** [comment]
Please, ask such questions in allure gitter https://gitter.im/allure-framework/allure-core
