### ISSUE TITLE
allure-js-commons: Unexpected endStep(). There are no any steps running

### ISSUE THREAD

**Issue by treyturner** [webdriverio-boneyard/wdio-allure-reporter#150]
Since upgrading to wdio v5, most of my test runs conclude with the following output spammed to stderr:

`[0-0] allure-js-commons: Unexpected endStep(). There are no any steps running`

This happens anywhere from a few to several hundred times depending on the length of the spec/suite, inhibiting analysis of the spec reporter output. I'm sure this is the result of code running outside of tests, but this seems expected for setup and teardown, no?

The issue was raised in the `allure-js-commons` repo (https://github.com/allure-framework/allure-js-commons/issues/21) but it was said that a fix would need to be found here.

I'm a little unclear as to the status of this reporter; it's still mentioned in the v5 docs, and I see it was moved to the new `@wdio/*` package namespace, but I also see that the code is in the boneyard. This reporter was useful to me and some of the non-engineering types in my org for v4, so it'd be great to have it as functional in v5.

**Comment by BorisOsipov** [comment]
>I'm a little unclear as to the status of this reporter

this reporter for v4. Reporter for v5 is on main wdio repo.

**Comment by treyturner** [comment]
@BorisOsipov Sorry, where? I posted here because I looked and couldn't find it, or what I did find had a post from you saying to report the issue here.

https://github.com/webdriverio/webdriverio/issues/2953

**Comment by BorisOsipov** [comment]
@treyturner 
> Sorry, where?... I did find had a post from you saying to report the issue here.

yes it was actual for old(v4.x) wdio releases issues. Now wdio v5 is monorepo and all issues for `@wdio/*` are here https://github.com/webdriverio/webdriverio/issues/new/choose here

**Comment by BorisOsipov** [comment]
@treyturner btw it is important to have repo with example how repoduce issue.

**Comment by treyturner** [comment]
Opened a new ticket with a reproducible example: https://github.com/webdriverio/webdriverio/issues/3386
