### ISSUE TITLE
2 tags are getting added for the same test case in case of pending state.

### ISSUE THREAD

**Issue by gitsilky** [webdriverio-boneyard/wdio-allure-reporter#30]

**Comment by just-boris** [comment]
Hello!
I need more information from you.
What test framework are you using? What do you mean as tags? I don't remember such concept in Allure

**Comment by gitsilky** [comment]
I am using cucumber Framework.If the test case gets failed at any step then rest of the steps gets pending and the allure report shows double number of pending testcases.If I open the xmls that gets generated after the execution then I find <test-case> "user goes to the homepage" <test-case> tag twice with status pending.So pending testcases gets doubled in the allure report.

**Comment by just-boris** [comment]
Well, that weird. The reason I guess the same as #26 has, but the effect is different. What `cucumber` and `wdio-cucumber-framework` do you have?

**Comment by gitsilky** [comment]
I am using 
wdio-cucumber-framework :- version: 0.2.5.
wdio-allure-reporter :- version: 0.1.2
cucumber :- version: 1.2.1.


[3aed57d8-8ba0-4a6d-a2dc-f186b9964685.txt](https://github.com/webdriverio/wdio-allure-reporter/files/505615/3aed57d8-8ba0-4a6d-a2dc-f186b9964685.txt)

**Comment by BorisOsipov** [comment]
Close due inactive.
